import type { useTranslations } from 'next-intl';

import type { PackageDef } from './types';

export const getPackages = (
  t: ReturnType<typeof useTranslations>,
): PackageDef[] => [
  {
    title: t('0.title'),
    price: t('0.price'),
    type: 'one-time',
    description: t('0.description'),
    details: [
      t('0.details.0'),
      t('0.details.1'),
      t('0.details.2'),
      t('0.details.3'),
      t('0.details.4'),
      t('0.details.5'),
      t('0.details.6'),
    ],
  },
  {
    title: t('1.title'),
    price: t('1.price'),
    type: 'one-time',
    description: t('1.description'),
    details: [
      t('1.details.0'),
      t('1.details.1'),
      t('1.details.2'),
      t('1.details.3'),
      t('1.details.4'),
      t('1.details.5'),
      t('1.details.6'),
      t('1.details.7'),
      t('1.details.8'),
      t('1.details.9'),
    ],
  },
  {
    title: t('2.title'),
    price: t('2.price'),
    type: 'one-time',
    description: t('2.description'),
    details: [
      t('2.details.0'),
      t('2.details.1'),
      t('2.details.2'),
      t('2.details.3'),
      t('2.details.4'),
      t('2.details.5'),
      t('2.details.6'),
      t('2.details.7'),
      t('2.details.8'),
      t('2.details.9'),
    ],
  },
  {
    title: t('3.title'),
    price: t('3.price'),
    type: 'one-time',
    description: t('3.description'),
    details: [
      t('3.details.0'),
      t('3.details.1'),
      t('3.details.2'),
      t('3.details.3'),
      t('3.details.4'),
      t('3.details.5'),
      t('3.details.6'),
      t('3.details.7'),
      t('3.details.8'),
      t('3.details.9'),
    ],
  },
  {
    title: t('4.title'),
    price: t('4.price'),
    type: 'subscription',
    description: t('4.description'),
    details: [
      t('4.details.0'),
      t('4.details.1'),
      t('4.details.2'),
      t('4.details.3'),
      t('4.details.4'),
      t('4.details.5'),
      t('4.details.6'),
    ],
  },
  {
    title: t('5.title'),
    price: t('5.price'),
    type: 'subscription',
    description: t('5.description'),
    details: [
      t('5.details.0'),
      t('5.details.1'),
      t('5.details.2'),
      t('5.details.3'),
      t('5.details.4'),
      t('5.details.5'),
      t('5.details.6'),
      t('5.details.7'),
      t('5.details.8'),
    ],
  },
  {
    title: t('6.title'),
    price: t('6.price'),
    type: 'subscription',
    description: t('6.description'),
    details: [
      t('6.details.0'),
      t('6.details.1'),
      t('6.details.2'),
      t('6.details.3'),
      t('6.details.4'),
      t('6.details.5'),
      t('6.details.6'),
      t('6.details.7'),
      t('6.details.8'),
    ],
  },
  {
    title: t('7.title'),
    price: t('7.price'),
    type: 'subscription',
    description: t('7.description'),
    details: [
      t('7.details.0'),
      t('7.details.1'),
      t('7.details.2'),
      t('7.details.3'),
      t('7.details.4'),
      t('7.details.5'),
      t('7.details.6'),
      t('7.details.7'),
      t('7.details.8'),
      t('7.details.9'),
      t('7.details.10'),
    ],
  },
];
