import type { PackageDef } from './types';

export const packages: PackageDef[] = [
  {
    title: 'Bronze HR Starter Package',
    price: '€4,500',
    type: 'one-time',
    description:
      'For businesses seeking an entry-level HR solution, this package covers the essentials of HR management, including recruitment strategy, basic compliance, and performance management systems.',
    details: [
      'Talent Sourcing & Recruitment Strategy',
      'Basic Employee Benefits Review',
      'Conflict Resolution Training',
      'Workplace Culture & Employee Engagement Assessment',
      'HR Policy Review & Updates',
      'Performance Management Systems Setup',
      'Employee Onboarding Process Development',
    ],
  },
  {
    title: 'Silver HR Essentials Package',
    price: '€7,500',
    type: 'one-time',
    description:
      'This package provides focused HR support to businesses needing assistance in specific HR areas, such as employee development and compliance. Ideal for companies that want key areas optimized for efficiency.',
    details: [
      'Employee Benefits Review',
      'Talent Acquisition & Screening',
      'Conflict Resolution & Mediation',
      'Workplace Culture Assessment',
      'Leadership & Management Training',
      'Employee Engagement Survey',
      'Performance Management & Feedback Systems',
      'Workplace Safety & Compliance',
      'Basic HR Policy Development',
      'Employee Satisfaction & Retention Programs',
    ],
  },
  {
    title: 'Gold HR Enhancement Package',
    price: '€10,000',
    type: 'one-time',
    description:
      'Designed for businesses looking for a comprehensive HR overhaul, this package provides high-level support across multiple HR functions, including recruitment, performance management, and conflict resolution.',
    details: [
      'Employee Benefits Review & Optimization',
      'Talent Sourcing & Recruitment Strategy',
      'Workplace Conflict Mediation & Training',
      'Leadership Development Program',
      'Performance Management Systems & Appraisals',
      'HR Legal Compliance & Risk Management',
      'Employee Engagement Strategy',
      'HR Policy Development & Compliance',
      'Workplace Safety & Health Compliance Audit',
      'Custom HR Strategy Recommendations',
    ],
  },
  {
    title: 'Platinum HR Solutions Package',
    price: '€15,000',
    type: 'one-time',
    description:
      'This package includes end-to-end HR services for large businesses that need a complete HR transformation, from recruitment and talent acquisition to leadership coaching and compliance audits. It ensures that your HR functions are fully optimized for success.',
    details: [
      'Full HR Consultation & Strategy Development',
      'Talent Acquisition & Recruitment Services',
      'Employee Benefits Optimization',
      'Leadership & Management Training',
      'Employee Engagement & Retention Strategies',
      'Workplace Conflict Resolution & Mediation',
      'HR Compliance & Risk Management',
      'Custom HR Policy Development',
      'Performance Management & Appraisal Systems',
      'One-Time HR Health Check & Audit',
    ],
  },
  {
    title: 'Essential HR Support Subscription',
    price: '€3,500',
    type: 'subscription',
    description:
      'A cost-effective option for businesses looking for consistent HR support across core areas. Ideal for companies that need foundational HR services focusing on key areas like compliance and benefits management.',
    details: [
      'Monthly HR Consultation Calls',
      'Basic Employee Benefits Review & Optimization',
      'Conflict Resolution & Mediation',
      'Employee Engagement Strategy',
      'HR Compliance Guidance',
      'Quarterly HR Health Check',
      'Workplace Culture Assessment',
    ],
  },
  {
    title: 'Comprehensive HR Solutions Subscription',
    price: '€5,500',
    type: 'subscription',
    description:
      'Perfect for businesses seeking regular HR assistance and support across recruitment, employee development, and compliance. This package provides ongoing solutions and tailored strategies to optimize HR processes.',
    details: [
      'Monthly HR Consultation & Assistance',
      'Employee Benefits Review & Optimization',
      'Workplace Conflict Mediation',
      'Leadership & Management Development Programs',
      'Ongoing Talent Sourcing & Screening',
      'Workplace Culture & Engagement Strategy',
      'HR Policy Development & Compliance Updates',
      'Employee Satisfaction & Retention Surveys',
      'Quarterly HR Performance Reports',
    ],
  },
  {
    title: 'Premium HR Support Subscription',
    price: '€7,500',
    type: 'subscription',
    description:
      'For businesses needing extensive HR support and ongoing development for leadership and employees. This package provides top-tier services and flexibility to ensure smooth HR operations and employee satisfaction.',
    details: [
      'Monthly HR Consultation & Support',
      'Leadership & Management Coaching',
      'Employee Benefits & Wellness Program Development',
      'Talent Acquisition & Recruitment Strategy',
      'Employee Engagement & Retention Initiatives',
      'Workplace Safety & Health Compliance',
      'Conflict Management & Resolution Training',
      'HR Compliance Audits',
      'Quarterly HR Performance Reviews',
    ],
  },
  {
    title: 'Elite HR Strategy Subscription',
    price: '€10,000',
    type: 'subscription',
    description:
      'Our Elite HR Strategy Subscription is the most comprehensive offering, providing all-encompassing HR services for large organizations. With this package, you receive dedicated HR experts available 24/7, full access to all our services, and bespoke HR strategies to ensure your company thrives across every HR function.',
    details: [
      'Full HR Consultation & Support 24/7',
      'Bespoke HR Strategy',
      'Comprehensive Employee Benefits & Wellness Program Management',
      'Ongoing Leadership & Management Development',
      'Talent Acquisition, Screening, and Recruitment',
      'Continuous Conflict Mediation & Resolution',
      'HR Legal Compliance & Risk Management',
      'Employee Engagement & Retention Strategies',
      'Customized Employee Development Plans',
      'Exclusive Executive Leadership Coaching',
      'Monthly HR Audits & Custom Reports',
    ],
  },
];
